{
 "title": "PythonMatcher",
 "time": { "from": "now/w", "to": "now/w" },
 "panels": [
  {
   "title": "Auctioneer price",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "auctioneer_prices",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "auctioneer_id", "operator": "=", "value": "Sim" }
     ]
    }
   ]
  },
  {
   "title": "Loads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "deviceagent_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceagent_id", "operator": "=", "value": "SimBatteryAgent" }
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "deviceagent_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceagent_id", "operator": "=", "value": "SimPVAgent" }
     ]
    },
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "deviceagent_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceagent_id", "operator": "=", "value": "SimLoadAgent" }
     ]
    }
   ]
  },
  {
   "title": "SOC Battery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deviceagent_soc",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "auctioneer_id", "operator": "=", "value": "Sim" }
     ]
    }
   ]
  }
 ]
}